// This file is auto-generated by @hey-api/openapi-ts

export const AppConfigSchema = {
    properties: {
        signup_enabled: {
            type: 'boolean',
            title: 'Signup Enabled'
        }
    },
    type: 'object',
    required: ['signup_enabled'],
    title: 'AppConfig',
    description: 'Public application configuration'
} as const;

export const Body_files_upload_fileSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_files-upload_file'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const EnqueueRequestSchema = {
    properties: {
        task: {
            type: 'string',
            enum: ['send_email', 'export_data', 'process_file'],
            title: 'Task'
        },
        queue: {
            type: 'string',
            enum: ['default', 'high', 'low'],
            title: 'Queue',
            default: 'default'
        },
        kwargs: {
            additionalProperties: true,
            type: 'object',
            title: 'Kwargs',
            default: {}
        }
    },
    type: 'object',
    required: ['task'],
    title: 'EnqueueRequest'
} as const;

export const EntraLoginRequestSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        tenant_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenant Id'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles',
            default: []
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'EntraLoginRequest'
} as const;

export const EntraLoginUrlResponseSchema = {
    properties: {
        login_url: {
            type: 'string',
            title: 'Login Url'
        }
    },
    type: 'object',
    required: ['login_url'],
    title: 'EntraLoginUrlResponse'
} as const;

export const FilePublicSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Filename'
        },
        content_type: {
            type: 'string',
            maxLength: 127,
            title: 'Content Type'
        },
        size: {
            type: 'integer',
            minimum: 0,
            title: 'Size'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['filename', 'content_type', 'size', 'id', 'owner_id'],
    title: 'FilePublic'
} as const;

export const FilesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FilePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FilesPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const JobInfoSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        func: {
            type: 'string',
            title: 'Func'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        queue: {
            type: 'string',
            title: 'Queue'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        ended_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ended At'
        }
    },
    type: 'object',
    required: ['id', 'func', 'status', 'queue'],
    title: 'JobInfo'
} as const;

export const JobStatusCountSchema = {
    properties: {
        queued: {
            type: 'integer',
            title: 'Queued',
            default: 0
        },
        started: {
            type: 'integer',
            title: 'Started',
            default: 0
        },
        finished: {
            type: 'integer',
            title: 'Finished',
            default: 0
        },
        failed: {
            type: 'integer',
            title: 'Failed',
            default: 0
        },
        deferred: {
            type: 'integer',
            title: 'Deferred',
            default: 0
        },
        canceled: {
            type: 'integer',
            title: 'Canceled',
            default: 0
        },
        stopped: {
            type: 'integer',
            title: 'Stopped',
            default: 0
        }
    },
    type: 'object',
    title: 'JobStatusCount'
} as const;

export const JobStatusResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        result: {
            title: 'Result'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['job_id', 'status'],
    title: 'JobStatusResponse'
} as const;

export const JobsListResponseSchema = {
    properties: {
        jobs: {
            items: {
                '$ref': '#/components/schemas/JobInfo'
            },
            type: 'array',
            title: 'Jobs'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['jobs', 'total'],
    title: 'JobsListResponse'
} as const;

export const JobsStatsResponseSchema = {
    properties: {
        status_counts: {
            '$ref': '#/components/schemas/JobStatusCount'
        },
        queue_stats: {
            items: {
                '$ref': '#/components/schemas/QueueStats'
            },
            type: 'array',
            title: 'Queue Stats'
        },
        total_jobs: {
            type: 'integer',
            title: 'Total Jobs'
        }
    },
    type: 'object',
    required: ['status_counts', 'queue_stats', 'total_jobs'],
    title: 'JobsStatsResponse'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MicrosoftTenantCreateSchema = {
    properties: {
        tenant_id: {
            type: 'string',
            maxLength: 255,
            title: 'Tenant Id'
        },
        tenant_name: {
            type: 'string',
            maxLength: 255,
            title: 'Tenant Name'
        },
        is_enabled: {
            type: 'boolean',
            title: 'Is Enabled',
            default: true
        },
        auto_create_users: {
            type: 'boolean',
            title: 'Auto Create Users',
            default: true
        }
    },
    type: 'object',
    required: ['tenant_id', 'tenant_name'],
    title: 'MicrosoftTenantCreate'
} as const;

export const MicrosoftTenantPublicSchema = {
    properties: {
        tenant_id: {
            type: 'string',
            maxLength: 255,
            title: 'Tenant Id'
        },
        tenant_name: {
            type: 'string',
            maxLength: 255,
            title: 'Tenant Name'
        },
        is_enabled: {
            type: 'boolean',
            title: 'Is Enabled',
            default: true
        },
        auto_create_users: {
            type: 'boolean',
            title: 'Auto Create Users',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        }
    },
    type: 'object',
    required: ['tenant_id', 'tenant_name', 'id'],
    title: 'MicrosoftTenantPublic'
} as const;

export const MicrosoftTenantUpdateSchema = {
    properties: {
        tenant_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenant Name'
        },
        is_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Enabled'
        },
        auto_create_users: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auto Create Users'
        }
    },
    type: 'object',
    title: 'MicrosoftTenantUpdate'
} as const;

export const MicrosoftTenantsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MicrosoftTenantPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MicrosoftTenantsPublic'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotificationCreateSchema = {
    properties: {
        type: {
            type: 'string',
            enum: ['info', 'success', 'warning', 'error'],
            title: 'Type',
            default: 'info'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        message: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Message'
        }
    },
    type: 'object',
    required: ['title', 'message'],
    title: 'NotificationCreate',
    description: 'Payload for sending a notification to the authenticated user.'
} as const;

export const NotificationSendSchema = {
    properties: {
        type: {
            type: 'string',
            enum: ['info', 'success', 'warning', 'error'],
            title: 'Type',
            default: 'info'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        message: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Message'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['title', 'message', 'user_id'],
    title: 'NotificationSend',
    description: 'Payload for superusers to push a notification to any user.'
} as const;

export const PermissionCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        resource: {
            type: 'string',
            maxLength: 255,
            title: 'Resource'
        }
    },
    type: 'object',
    required: ['name', 'resource'],
    title: 'PermissionCreate'
} as const;

export const PermissionDefinitionSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        display: {
            type: 'string',
            title: 'Display'
        },
        resource: {
            type: 'string',
            title: 'Resource'
        }
    },
    type: 'object',
    required: ['name', 'display', 'resource'],
    title: 'PermissionDefinition',
    description: 'Type definition for a permission.'
} as const;

export const PermissionPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        resource: {
            type: 'string',
            maxLength: 255,
            title: 'Resource'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'resource', 'id'],
    title: 'PermissionPublic'
} as const;

export const PermissionUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        resource: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resource'
        }
    },
    type: 'object',
    title: 'PermissionUpdate'
} as const;

export const PermissionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PermissionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PermissionsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const QueueStatsSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['name', 'count'],
    title: 'QueueStats'
} as const;

export const RoleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_system: {
            type: 'boolean',
            title: 'Is System',
            default: false
        },
        permission_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Permission Ids'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoleCreate'
} as const;

export const RolePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_system: {
            type: 'boolean',
            title: 'Is System',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        permissions: {
            items: {
                '$ref': '#/components/schemas/PermissionPublic'
            },
            type: 'array',
            title: 'Permissions'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'RolePublic'
} as const;

export const RoleUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        permission_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Permission Ids'
        }
    },
    type: 'object',
    title: 'RoleUpdate'
} as const;

export const RolesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RolePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RolesPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        azure_user_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Azure User Id'
        },
        azure_tenant_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Azure Tenant Id'
        },
        azure_roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Azure Roles',
            default: []
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;