// This file is auto-generated by @hey-api/openapi-ts

/**
 * Public application configuration
 */
export type AppConfig = {
    signup_enabled: boolean;
};

export type Body_files_upload_file = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type EnqueueRequest = {
    task: 'send_email' | 'export_data' | 'process_file';
    queue?: 'default' | 'high' | 'low';
    kwargs?: {
        [key: string]: unknown;
    };
};

export type task = 'send_email' | 'export_data' | 'process_file';

export type queue = 'default' | 'high' | 'low';

export type EntraLoginRequest = {
    access_token: string;
    tenant_id?: (string | null);
    roles?: Array<(string)>;
};

export type EntraLoginUrlResponse = {
    login_url: string;
};

export type FilePublic = {
    filename: string;
    content_type: string;
    size: number;
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type FilesPublic = {
    data: Array<FilePublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type JobInfo = {
    id: string;
    func: string;
    status: string;
    queue: string;
    created_at?: (string | null);
    started_at?: (string | null);
    ended_at?: (string | null);
};

export type JobsListResponse = {
    jobs: Array<JobInfo>;
    total: number;
};

export type JobsStatsResponse = {
    status_counts: JobStatusCount;
    queue_stats: Array<QueueStats>;
    total_jobs: number;
};

export type JobStatusCount = {
    queued?: number;
    started?: number;
    finished?: number;
    failed?: number;
    deferred?: number;
    canceled?: number;
    stopped?: number;
};

export type JobStatusResponse = {
    job_id: string;
    status: string;
    result?: unknown;
    error?: (string | null);
};

export type Message = {
    message: string;
};

export type MicrosoftTenantCreate = {
    tenant_id: string;
    tenant_name: string;
    is_enabled?: boolean;
    auto_create_users?: boolean;
};

export type MicrosoftTenantPublic = {
    tenant_id: string;
    tenant_name: string;
    is_enabled?: boolean;
    auto_create_users?: boolean;
    id: string;
    created_at?: (string | null);
    created_by?: (string | null);
};

export type MicrosoftTenantsPublic = {
    data: Array<MicrosoftTenantPublic>;
    count: number;
};

export type MicrosoftTenantUpdate = {
    tenant_name?: (string | null);
    is_enabled?: (boolean | null);
    auto_create_users?: (boolean | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Payload for sending a notification to the authenticated user.
 */
export type NotificationCreate = {
    type?: 'info' | 'success' | 'warning' | 'error';
    title: string;
    message: string;
};

export type type = 'info' | 'success' | 'warning' | 'error';

/**
 * Payload for superusers to push a notification to any user.
 */
export type NotificationSend = {
    type?: 'info' | 'success' | 'warning' | 'error';
    title: string;
    message: string;
    user_id: string;
};

export type PermissionCreate = {
    name: string;
    description?: (string | null);
    resource: string;
};

/**
 * Type definition for a permission.
 */
export type PermissionDefinition = {
    name: string;
    display: string;
    resource: string;
};

export type PermissionPublic = {
    name: string;
    description?: (string | null);
    resource: string;
    id: string;
    created_at?: (string | null);
};

export type PermissionsPublic = {
    data: Array<PermissionPublic>;
    count: number;
};

export type PermissionUpdate = {
    name?: (string | null);
    description?: (string | null);
    resource?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QueueStats = {
    name: string;
    count: number;
};

export type RoleCreate = {
    name: string;
    description?: (string | null);
    is_system?: boolean;
    permission_ids?: Array<(string)>;
};

export type RolePublic = {
    name: string;
    description?: (string | null);
    is_system?: boolean;
    id: string;
    created_at?: (string | null);
    permissions?: Array<PermissionPublic>;
};

export type RolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type RoleUpdate = {
    name?: (string | null);
    description?: (string | null);
    permission_ids?: (Array<(string)> | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    azure_user_id?: (string | null);
    azure_tenant_id?: (string | null);
    azure_roles?: Array<(string)>;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminGetJobsStatsResponse = (JobsStatsResponse);

export type AdminGetJobsListData = {
    limit?: number;
    queue?: string;
    statusFilter?: (string | null);
};

export type AdminGetJobsListResponse = (JobsListResponse);

export type AuthEntraEntraLoginData = {
    requestBody: EntraLoginRequest;
};

export type AuthEntraEntraLoginResponse = (Token);

export type AuthEntraGetEntraLoginUrlData = {
    redirectUri: string;
    tenantId?: (string | null);
};

export type AuthEntraGetEntraLoginUrlResponse = (EntraLoginUrlResponse);

export type AuthEntraGetEntraConfigResponse = ({
    [key: string]: unknown;
});

export type FilesUploadFileData = {
    formData: Body_files_upload_file;
};

export type FilesUploadFileResponse = (FilePublic);

export type FilesListFilesData = {
    limit?: number;
    skip?: number;
};

export type FilesListFilesResponse = (FilesPublic);

export type FilesGetFileData = {
    id: string;
};

export type FilesGetFileResponse = (FilePublic);

export type FilesDeleteFileData = {
    id: string;
};

export type FilesDeleteFileResponse = (Message);

export type FilesDownloadFileData = {
    id: string;
};

export type FilesDownloadFileResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NotificationsSendNotificationData = {
    requestBody: NotificationSend;
};

export type NotificationsSendNotificationResponse = (Message);

export type NotificationsSendNotificationToSelfData = {
    requestBody: NotificationCreate;
};

export type NotificationsSendNotificationToSelfResponse = (Message);

export type NotificationsSendTestNotificationToAllResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RbacListPermissionsData = {
    limit?: number;
    skip?: number;
};

export type RbacListPermissionsResponse = (PermissionsPublic);

export type RbacCreatePermissionEndpointData = {
    requestBody: PermissionCreate;
};

export type RbacCreatePermissionEndpointResponse = (PermissionPublic);

export type RbacGetPermissionEndpointData = {
    permissionId: string;
};

export type RbacGetPermissionEndpointResponse = (PermissionPublic);

export type RbacUpdatePermissionEndpointData = {
    permissionId: string;
    requestBody: PermissionUpdate;
};

export type RbacUpdatePermissionEndpointResponse = (PermissionPublic);

export type RbacDeletePermissionEndpointData = {
    permissionId: string;
};

export type RbacDeletePermissionEndpointResponse = ({
    [key: string]: (string);
});

export type RbacListRolesData = {
    limit?: number;
    skip?: number;
};

export type RbacListRolesResponse = (RolesPublic);

export type RbacCreateRoleEndpointData = {
    requestBody: RoleCreate;
};

export type RbacCreateRoleEndpointResponse = (RolePublic);

export type RbacGetRoleEndpointData = {
    roleId: string;
};

export type RbacGetRoleEndpointResponse = (RolePublic);

export type RbacUpdateRoleEndpointData = {
    requestBody: RoleUpdate;
    roleId: string;
};

export type RbacUpdateRoleEndpointResponse = (RolePublic);

export type RbacDeleteRoleEndpointData = {
    roleId: string;
};

export type RbacDeleteRoleEndpointResponse = ({
    [key: string]: (string);
});

export type RbacAddPermissionToRoleEndpointData = {
    permissionId: string;
    roleId: string;
};

export type RbacAddPermissionToRoleEndpointResponse = ({
    [key: string]: (string);
});

export type RbacRemovePermissionFromRoleEndpointData = {
    permissionId: string;
    roleId: string;
};

export type RbacRemovePermissionFromRoleEndpointResponse = ({
    [key: string]: (string);
});

export type RbacAssignRoleToUserEndpointData = {
    roleId: string;
    userId: string;
};

export type RbacAssignRoleToUserEndpointResponse = ({
    [key: string]: (string);
});

export type RbacRemoveRoleFromUserEndpointData = {
    roleId: string;
    userId: string;
};

export type RbacRemoveRoleFromUserEndpointResponse = ({
    [key: string]: (string);
});

export type RbacGetUserRolesEndpointData = {
    userId: string;
};

export type RbacGetUserRolesEndpointResponse = (RolesPublic);

export type RbacGetUserPermissionsEndpointData = {
    userId: string;
};

export type RbacGetUserPermissionsEndpointResponse = (PermissionsPublic);

export type RbacGetPermissionsCatalogResponse = ({
    [key: string]: Array<PermissionDefinition>;
});

export type TasksEnqueueTaskData = {
    requestBody: EnqueueRequest;
};

export type TasksEnqueueTaskResponse = (JobStatusResponse);

export type TasksGetJobStatusData = {
    jobId: string;
};

export type TasksGetJobStatusResponse = (JobStatusResponse);

export type TasksCancelJobData = {
    jobId: string;
};

export type TasksCancelJobResponse = ({
    [key: string]: (string);
});

export type TenantsListTenantsData = {
    limit?: number;
    skip?: number;
};

export type TenantsListTenantsResponse = (MicrosoftTenantsPublic);

export type TenantsCreateTenantData = {
    requestBody: MicrosoftTenantCreate;
};

export type TenantsCreateTenantResponse = (MicrosoftTenantPublic);

export type TenantsUpdateTenantData = {
    requestBody: MicrosoftTenantUpdate;
    tenantId: string;
};

export type TenantsUpdateTenantResponse = (MicrosoftTenantPublic);

export type TenantsDeleteTenantData = {
    tenantId: string;
};

export type TenantsDeleteTenantResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsGetAppConfigResponse = (AppConfig);