"""add Microsoft Entra models

Revision ID: 9ca0f5177345
Revises: fe56fa70289e
Create Date: 2026-02-23 20:54:45.950009

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ca0f5177345'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microsofttenant',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tenant_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_create_users', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microsofttenant_tenant_id'), 'microsofttenant', ['tenant_id'], unique=True)
    op.create_table('usertenantrole',
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['microsofttenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('azure_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('azure_tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('azure_roles', sa.JSON(), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.create_index(op.f('ix_user_azure_user_id'), 'user', ['azure_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_azure_user_id'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('user', 'azure_roles')
    op.drop_column('user', 'azure_tenant_id')
    op.drop_column('user', 'azure_user_id')
    op.drop_table('usertenantrole')
    op.drop_index(op.f('ix_microsofttenant_tenant_id'), table_name='microsofttenant')
    op.drop_table('microsofttenant')
    # ### end Alembic commands ###
